// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive_ce.dart';
import 'package:expense_tracker_app/features/budgets/models/budget.dart';
import 'package:expense_tracker_app/features/transaction/model/transaction.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(BudgetAdapter());
    registerAdapter(CategoryTypeAdapter());
    registerAdapter(RecurrenceTypeAdapter());
    registerAdapter(TransactionModelAdapter());
    registerAdapter(TransactionTypeAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(BudgetAdapter());
    registerAdapter(CategoryTypeAdapter());
    registerAdapter(RecurrenceTypeAdapter());
    registerAdapter(TransactionModelAdapter());
    registerAdapter(TransactionTypeAdapter());
  }
}
